enum DataIndex {
  first_name = "Prénom",
  last_name = "Nom",
  email = "E-mail",
  login = "Email / Mot de passe",
  name = "Nom Affiché",
  password = "Mot de passe",
  newpassword_1 = "Nouveau mot de passe",
  newpassword_2 = "Confirmer le nouveau mot de passe",
  address_1 = "Numéro et nom de rue",
  address_2 = "Bâtiment, appartement, lot, etc. (facultatif)",
  city = "Ville",
  country = "Pays",
  postecode = "Code postale",
  state = "Région",
  phone = "Téléphone",
  company = "Nom de l’entreprise (facultatif)",
  saveModification = "Envoyer les modification",
  billing = "Adresse de Facturation",
  shipping = "Adresse de Livraison",
  orderHistory = "Historique de mes commandes",
  sub_total = "Sous total",
  total = "Total",
  order_date = "Date d'achat",
  date_completed = "Délévré le",
  items = "Articles",
  sub_total_items = "Sous total produits",
  shippins_fees = "Frais de livraison  ",
  payemnt_details = "Mode de paiement",
  shipping_details = "Mode de livraison",
  evalute_products = "Evaluer",
  note = "Votre note",
  enter_your_review = "Entrer Votre avis",
  currency = "Dh",
}

export default DataIndex;
